### ISSUE TITLE
Plans to migrate to use Managed identities instead of Storage account Access Keys?

### ISSUE THREAD

**Issue by VOVELEE** [microsoft/fhir-loader#12]
I know that this is an open source project but still I would like to understand are there plans to migrate the current storage account authorization mechanism to use Managed identities (e.g. System managed identity on the Azure Function) instead of Access Keys?

This will be great addition in environments which have to follow strict hardening rules. (e.g. centralized RBAC management)

_Microsoft recommends using Azure Active Directory (Azure AD) to authorize requests against blob and queue data if possible, rather than using the account keys (Shared Key authorization)._

**Comment by mikaelweave** [comment]
This has been completed! 👍🏽
