### ISSUE TITLE
Issue while deploying Fhirloader following the ahds-workshop instructions

### ISSUE THREAD

**Issue by SD-14** [microsoft/fhir-loader#18]
Hello,

I tried following the instructions from AHDS-Workshop: https://github.com/microsoft/azure-health-data-services-workshop & came across an issue where the Fhir-loader keeps having a conflict during deployment. It seemed to be working well and fine up until last week, when I noticed this and thought it was a deployment issue from my end, but then tried redeploying it in multiple regions, and got the same error again:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/83011430/194842623-b174498d-bc67-4f30-9bd6-745ec76e4867.png">

Not sure what I'm missing out on, or if anybody could help that would be great!

**Comment by evachen96** [comment]
Hi @SD-14 ! Are you still facing this issue?

**Comment by mikaelweave** [comment]
Closing due to lack of response.
