### ISSUE TITLE
Recommend Changes to deployment scripts for Event Grid

### ISSUE THREAD

**Issue by ms-mikerice** [microsoft/fhir-loader#22]
In working with customer on debugging, I'm recommending that the deployment script be changed.
When the Event Grid is deployed, dead lettering should be enabled by default and diagnostics should be turned on and routed to storage by default. This helps with debugging.

**Comment by mikaelweave** [comment]
@sordahl-ga - Any thoughts on this?

**Comment by sordahl-ga** [comment]
We have moved event grid binding to storage queues this allows for greater resiliency and debug traceability.  I will mark this as closed if no further comment is received
