### ISSUE TITLE
Divide By Zero Error in ImportUtils Telemetry Calculation

### ISSUE THREAD

**Issue by DustinEwers** [microsoft/fhir-loader#23]
This line throws divide by zero errors when the elapsed milliseconds are under 1000. 

https://github.com/microsoft/fhir-loader/blob/bd42723d719f245d5a1e2f38093856713ae3ac71/FHIRBulkImport/ImportUtils.cs#L75

You could get a proper double by alerting "1000" to "1000d" to make a double literal. Otherwise, a long divided by a number bigger than it returns 0, which is generally frowned upon as a divisor. 

Example:

`using System;

class Program {
  public static void Main (string[] args) {
    long milli = 10;
    Console.WriteLine(milli / 1000); // Outputs 0
    
    double dbl = milli / 1000;
    Console.WriteLine(dbl); // Outputs 0
    
    double dbl2 = milli / 1000d;
    Console.WriteLine(dbl2); // Outputs 0.01    
  }
}`

**Comment by evachen96** [comment]
Thanks for reaching out! We refactored with telemetry client and the line here no longer exists in main. Closing this out.
