### ISSUE TITLE
How can I make bundles for the patients in SQL Server Database?

### ISSUE THREAD

**Issue by Kedar782** [microsoft/fhir-loader#28]
I have all of my data in SQL Server. (around 20000 patients)
I want to transfer all of my data into the Azure API for FHIR. I have used Azure API for FHIR and proxy.
I think I can follow this repo for the data ingestion but how can I make bundles for my data on the SQL server.

I will really appreciate your help on this.

**Comment by evachen96** [comment]
Hi @Kedar782!

You can try using Data Factory Mapper  (https://learn.microsoft.com/en-us/azure/data-factory/concepts-data-flow-overview), or write a program to convert data from SQL to FHIR JSON. At a high level, it would look like this:

1. Install the Hl7.Fhir.Core NuGet package to your project.
2. 1. Create a connection to the SQL database using ADO.NET.
3. 2. Execute an SQL query to retrieve the patient data from the database.
4. 3. Create a list of Patient FHIR resources and populate it with the patient data.
5. 4. Create a FHIR Bundle and add the Patient resources to it.
6. 5. Serialize the FHIR Bundle to a JSON or XML string.

Hope this helps!

**Comment by Kedar782** [comment]
Hello eva,

Can I use this project to insert data from the Azure API for FHIR to Sql Server?

Regards,
Kedarnath Shinde
