### ISSUE TITLE
Issue: 'Resource Group...could not be found' error occurred while running deployFhirBulk.bash script

### ISSUE THREAD

**Issue by rsliang** [microsoft/fhir-loader#33]
**Describe the Issue **
When running deployFhirBulk.bash script from 'scripts' directory in cloud shell, it failed with the below 'resource group ...could not be found' error:
...
Creating MSI for FHIR Bulk Loader & Export Function App...
Setting KeyVault Policy to allow secret access for FHIR Bulk Loader & Export App...
ERROR: (ResourceGroupNotFound) Resource group 'spring-petclinic-microservices' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'spring-petclinic-microservices' could not be found.
...

Resolution: I was able to successfully run this script by adding resource group parameter to the az keyvault command at line 684 as follows:
	stepresult=$(az keyvault set-policy -g $resourceGroupName -n $keyVaultName --secret-permissions list get set --object-id $msi)

Steps to reproduce:
1) Open Azure Cloud Shell
2) CD to scripts directory
3) Run ./deployFhirBulk.bash
4) Enter and confirm script parameters
5) Script execution failed with 'resource group...could not be found' error

**Comment by evachen96** [comment]
Hi @rsliang, thanks for submitting this issue! The engineering team is not able to reproduce this issue, we're able to deploy succcessfully with the current script. Are you still facing this issue?

**Comment by mikaelweave** [comment]
Closing due to lack of response.
