### ISSUE TITLE
microsoft-fhir-loader for hl7.fhir.us.core#6.0.0 receives "Package type IG is not valid."

### ISSUE THREAD

**Issue by enjoysparkling** [microsoft/fhir-loader#40]
**hl7.fhir.us.core#6.0.0 is being skipped when using microsoft-fhir-loader command **
I was able to load a few other packages, including the hl7.fhir.core#4.0.1, but the latest US Core is being skipped.

I am attempting to load them to an Azure HDS FHIR service running FHIR R4.

```
13:37:49 info: FhirLoader.CommandLineTool.Program[0] Setting up Microsoft FHIR Loader Tool, please wait...
13:37:49 info: FhirLoader.CommandLineTool.Program[0] Attempting to get access token for https://xxx.fhir.azurehealthcareapis.com/ with scopes https://xxx.fhir.azurehealthcareapis.com//user_impersonation...
13:38:06 info: FhirLoader.CommandLineTool.Program[0] Got token for FHIR server https://xxx.fhir.azurehealthcareapis.com/!
13:38:06 info: FhirLoader.CommandLineTool.Program[0] Searching ~\.fhir\packages\hl7.fhir.us.core#6.0.0\package for FHIR package files.
13:38:06 fail: FhirLoader.CommandLineTool.Program[0] Package type IG is not valid. Skipping the loading process.
13:38:06 fail: FhirLoader.CommandLineTool.Program[0] Package type IG is not valid. Skipping the loading process.
Package type IG is not valid. Skipping the loading process.
```

Steps to reproduce:
1. Download hl7.fhir.us.core#6.0.0 from Simplifier (I used the firely terminal)
2. Execute `microsoft-fhir-loader --package "~\.fhir\packages\hl7.fhir.us.core#6.0.0\package" --fhir "https://myserver.fhir.azurehealthcareapis.com"` 

The `--debug` argument didn't produce any additional output.  Is there something I should be looking for?  My package directory has, among 200+ other JSON files:
- .index.json
- package.json
- ImplementationGuide-hl7.fhir.us.core.json

**Comment by enjoysparkling** [comment]
Looking into this a bit, based on the error message it seems like inside the `package.json` the FhirLoader is looking for a specific value in the `type` key:value pair.  

I am seeing these "type" : "VALUE" pairs in each of `package.json` files in the packages and status if they loaded or skipped:
(Note, these are all the package dependencies for the hl7.fhir.us.core + my package (Signal)
- ✅ Loaded:  `hl7.fhir.r4.core` with `"type": "fhir.core"`
- ❌ Skipped:  `hl7.fhir.us.core` with `"type" : "IG"`
- ✅ Loaded: `hl7.fhir.uv.bulkdata` with `"type": "fhir.ig"`
- ❌ Skipped:  `hl7.fhir.uv.sdc` with `"type": "IG"`
- ❌ Skipped:  `hl7.fhir.uv.smart-app-launch` with `"type" : "IG"`
- ❌ Skipped:  `hl7.terminology.r4` with `"type": "IG"`
- ❌ Skipped:  `ihe.formatcode.fhir` with `"type": "IG"`
- ❌ Skipped:  `signal.core.r4` with `type` key:value is **absent**
- ✅ Loaded:  `us.cdc.phinvads` with `"type": "Conformance"`
- ✅ Loaded:  `us.nlm.vsac` with `"type": "Conformance"`

What are the valid `type` values in `package.json` for FhirLoader.CommandLineTool?  And why are these VERY public ones not working at this time?  Should these additional values be added as valid for the tool?

**Comment by enjoysparkling** [comment]
I think I isolated the issue to this line of code:  
https://github.com/microsoft/fhir-loader/blob/67ca8af8e4a67aa5404ee97c551e1f4065542a41/src/FhirLoader.CommandLineTool/FileSource/PackageType.cs#L11-L21

Based on [Packages - FHIR v5.0.0](http://hl7.org/fhir/packages.html) `type` is "recommended" (not required), and the values should have no impact on tools using the package.  So, I think this whole portion could/should be removed, correct?

My C# skills are limited, and I am not sure how this is used in other parts of the code.  But would it be as simple as commenting it out so that part is not evaluated?

**Comment by evachen96** [comment]
Hi @enjoysparkling - the CLI tool was in a branch in an experimental capacity, we are now deferring to another tool https://github.com/brianpos/UploadFIG which is more robust. Thanks!
