### ISSUE TITLE
Unable to load Organization model data via FHIR Loader.

### ISSUE THREAD

**Issue by subhashrin** [microsoft/fhir-loader#41]
**Describe the Issue **
I am trying to get the Organization model data(entire) in FHIR Loader. 
There is no direct connection for Organization model with Patient model.
Since there is no patient related entities(Patient model) in the organization, facing some issues to get the data.

To Export from Source used this template:
{
                "query": "Patient?_count=50",
                "patientreferencefield":"id",
                "include": [
                                "Encounter?patient=$IDS&_count=50",
                                "Patient?_id=$IDS&_count=50"
                ]
}

I can see this note from Document but still wanted to know if there is any way.
**note:**
**Con: Patient-centric - Only able to export patient entities and those linked to patient entities.**

Appreciate your help by giving your comments/feedbacks.
Thank you!

**Comment by evachen96** [comment]
Hi @subhashrin ! Yes, you are correct, the Organization resource doesn't have any reference to Patient ID, but the FHIR Loader is patient-centric export. You can consider running $export from your FHIR server and then running https://{{FHIR_URL}}/$export?_type=Organization command to export the organization data as an alternative to the FHIR Loader export. Thanks!
