### ISSUE TITLE
Azure FHIR Bulk Loader Issue - Unhandled Error:Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by NeerajSAS** [microsoft/fhir-loader#42]
**Describe the Issue **
I configured an Azure API for FHIR and successfully tested Import and export using Postman.
I then wanted to install Azure FHIR Bulk Loader tool and followed the Web Portal option to automatically deploy the tool.

I tried to upload a bundle file, however after a few min in bundleserr I can an error file with the response as "Unhandled Error:Invalid URI: The hostname could not be parsed."

Steps to reproduce
1. Installed FHIR Loader tool using the "Deploy to Azure" automatic option
2. I have also provided Storage BLOB Data contributor role to the storage account for the FHIR API.
3. Uploaded a FHIR Bundle file
4. Minutes later I can see bundleserr folder has the file with error response "Unhandled Error:Invalid URI: The hostname could not be parsed."

Can you please provide guidance to resolve this issue. we are planning to demo this functionality to a potential customer who will be leveraging Azure API for FHIR offering after the successful demo.

This issue is a show stopper for us to proceed with the demo.

Kindly help.

Thansk
Neeraj.

**Comment by NeerajSAS** [comment]
Hi Can some one please respond, Azure support team referred me to log an issue here, Please note that Azure does not support $import to process bundle files and if you try to upload bundle files via options like POSTMAN you hit an issue related to 500 bundle size limit which the azure suupport\product do not want to increase

It will be very helpful if you provide some inputs\pointers that can help resolve the issue.
Error:Invalid URI: The hostname could not be parsed."

**Comment by sordahl-ga** [comment]
@NeerajSAS please redeploy using the CLI Deployment Instructions for direct FHIR Server Access as detailed here: https://github.com/microsoft/fhir-loader#cli-deployment you will also need to use Service Principal to access the services.  The bicep templates are out of date for portal deployment and are actively being worked on.

**Comment by NeerajSAS** [comment]
Thanks I tried that , however getting this below error 

++ az keyvault create --name kv-bulk17289 --resource-group duke-rg --location eastus2 --tags 'HealthArchitectures = FHIRBulk' --output none
ERROR: (RequestDisallowedByPolicy) Resource 'kv-bulk17289' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Deny public network access to Key Vaults","id":"/providers/Microsoft.Management/managementGroups/mg-zone2/providers/Microsoft.Authorization/policyAssignments/sas-cis-publickv-policy"},"policyDefinition":{"name":"Audit/Deny public network access to Key Vaults","id":"/providers/Microsoft.Management/managementgroups/mg-base/providers/Microsoft.Authorization/policyDefinitions/sas-cis-publickv-policy"}}]'.


I am the owner of the subscription so not sure why getting this error

Please advise.

Thanks,
Neeraj.

**Comment by sordahl-ga** [comment]
This has to do with policy defined in your subscriptionby your organizaation to not allow keyvault access over public networks.  You will need to run the installation scripts from a machine that is attached an allowed VNET or VPN client.  Running from cloud shell is by default a public network.
