### ISSUE TITLE
Unhandled Error:The type initializer for 'FHIRBulkImport.FHIRUtils' threw an exception.Issue

### ISSUE THREAD

**Issue by NeerajSAS** [microsoft/fhir-loader#54]
FHIR Loader tool not able to process files:-

1. After we upload NDJSON files in bundles folder, we can see them getting split successfully however after couple of minutes they are getting moved into bundleserr folder with the following error message in the response files

Unhandled Error:The type initializer for 'FHIRBulkImport.FHIRUtils' threw an exception.
   at FHIRBulkImport.FHIRUtils.CallFHIRServer(String path, String body, HttpMethod method, ILogger log, String customAudience) in C:\home\site\repository\FHIRBulkImport\FHIRUtils.cs:line 62
   at FHIRBulkImport.ImportUtils.ImportBundle(String name, ILogger log, TelemetryClient telemetryClient) in C:\home\site\repository\FHIRBulkImport\ImportUtils.cs:line 101

Frankly since this tool is not supported by Azure it being open source, it took couple of weeks for us to get to this point earlier we used to get all kinds of key vault security error and when we managed to resolve all those we are hitting this show stopper.

Please provide help as we are working on a client project that  requires this feature.

**Comment by evachen96** [comment]
@NeerajSAS Thanks for reporting this issue, we will take a look and let you know!

**Comment by evachen96** [comment]
HI @NeerajSAS  - we were not able to repro this issue. Can you make sure that you are uploading the NDJSON file in the NDJSON container, rather than directly in the bundle container? Let us know if that works; if not, we may need to get more detailed steps to try and repro the issue.
