### ISSUE TITLE
Issue: FHIR bulk loader functionality not picking up .ndjson files from Azure blob storage.

### ISSUE THREAD

**Issue by saurabhmandel** [microsoft/fhir-loader#55]
We have a container in blob storage where we are putting our ndjson files. As soon as the file comes into the container, the FHIR bulk loader should pick it up and load it in FHIR server. It was working fine before our service principal client secret got expired and we found out that our blob storage access key got expired. We have updated these both since in the key vault and still we are facing the issue that the FHIR bulk loader is not picking up the ndjson files from the container.

**Comment by erikhoward** [comment]
@saurabhmandel - we've just made a commit that should fix your issue with .ndjson files not being picked up from Azure blob storage. Please pull the latest code and try again.

**Comment by saurabhmandel** [comment]
Hi Eric Howard,

Just I have one question regarding this latest code just want to make sure that I am doing it correctly, I have pulled the latest repo as you mentioned so do I need to deploy a completely new FHIR bulk loader service or after pulling the latest code it will just work with old one ?

Thanks,
Saurabh
________________________________

**Comment by evachen96** [comment]
@saurabhmandel You will need to redeploy a new FHIR bulk loader service. Let us know if that works!

**Comment by evachen96** [comment]
@saurabhmandel I will close this issue for now, please re-open if the issue persists!
