### ISSUE TITLE
How to use this project to export and Import data from traditional Sql server database.

### ISSUE THREAD

**Issue by Kedar782** [microsoft/fhir-loader#60]
How can I use this project to import data from the Sql server database into Azure API for FHIR. I'm also using the Microsoft FHIR-proxy for the ONC G 10 certification.
My EMR uses Sql Server database. I want to import data from sql server and insert it into the Azure API for FHIR. Also, I want to add new data added into FHIR into the SQL server.

Please guide me how can I achieve this?

I will really appreciate your help on this.

Regards,
Kedarnath Shinde

**Comment by evachen96** [comment]
Thanks for your question @Kedar782 , the engineering team will look into this and get back to you!

**Comment by evachen96** [comment]
@Kedar782  Please refer to previous response: https://github.com/microsoft/fhir-loader/issues/28#issuecomment-1461140315
