### ISSUE TITLE
Getting Issue for Portal Deployment.

### ISSUE THREAD

**Issue by Kedar782** [microsoft/fhir-loader#61]
Getting this error when I deploy the code using the Deploy to Portal option On Azure API for FHIR.

{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template variable 'fhirResourceGroupName' is not valid: The language expression property array index '4' is out of bounds.. Please see https://aka.ms/arm-functions for usage details.'."}

**Comment by evachen96** [comment]
The engineering team will look into this and get back!

**Comment by Kedar782** [comment]
@evachen96 
I tried to look into the Azure API for FHIR database using POSTMAN Get API for Patients in bundle file and I cannot see the Patient in the Azure API for FHIR.
Did I do something wrong in the installation?
Please let me know.

**Comment by Kedar782** [comment]
@evachen96 

Please follow this issue also. Here I used Azure API for FHIR (No Proxy URL) and SP.

https://github.com/microsoft/fhir-loader/issues/63#issue-2272682925

**Comment by Kedar782** [comment]
I made it work but still has some issue.
Please go to this issue. https://github.com/microsoft/fhir-loader/issues/63#issue-2272682925
